config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True

# запуск dbt dbt compile --profiles-dir ./  -m "tag:dau"
default:
  outputs:
    dev:
      type: postgres
      threads: 3
      host: localhost
      port: 5432
      user: shpz
      pass: "12345"
      dbname: tmp
      schema: stg
    duckdb:
      type: duckdb
      schema: ods
      path: '~/Downloads/dbt.duckdb'
      extensions:
        - postgres
        - httpfs
        - parquet
  target: dev
