config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True

# запуск dbt dbt compile --profiles-dir ./  -m "tag:dau"
default:
  outputs:
    dev:
      type: postgres
      threads: 3
      host: localhost
      port: 5432
      user: shpz
      pass: "12345"
      dbname: tmp
      schema: stg
  target: dev

duckdb:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '~/Downloads/dbt.duckdb'
      extensions:
        - postgres
        - httpfs
        - parquet
      settings:
        s3_region: ""
        s3_access_key_id: "{{ env_var('S3_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('S3_SECRET_ACCESS_KEY') }}"
        s3_endpoint: "127.0.0.1:9002"