config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True

# запуск dbt dbt compile --profiles-dir ./  -m "tag:dau"
default:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: shpz
      pass: "12345"
      dbname: dwh
      schema: stg
    archimedes:
      type: postgres
      threads: 1
      host: 192.168.55.102
      port: 5432
      user: user
      pass: "12345"
      dbname: dwh
      schema: stg
  target: dev
