{{ config(
 tags=['raw_products', 'products', 'raw'],
 target='duckdb',
 schema='raw',
 materialized='table',
) }}

SELECT
product_id,
p.offer_id,
is_fbo_visible,
is_fbs_visible,
archived,
p.is_discounted,
id,
name,
barcode,
buybox_price,
category_id,
created_at,
images,
marketing_price,
min_ozon_price,
old_price,
premium_price,
price,
recommended_price,
min_price,
sources,
stocks,
errors,
vat,
visible,
visibility_details,
price_index,
commissions,
volume_weight,
is_prepayment,
is_prepayment_allowed,
images360,
color_image,
primary_image,
status,
state,
service_type,
CASE WHEN fbo_sku = 0 THEN sku ELSE fbo_sku END AS fbo_sku,
CASE WHEN fbs_sku = 0 THEN sku ELSE fbs_sku END AS fbs_sku,
currency_code,
is_kgt,
discounted_stocks,
has_discounted_item,
barcodes,
updated_at,
price_indexes,
sku,
description_category_id,
type_id
FROM {{ ref('raw_products_list') }} p
JOIN {{ ref('raw_products_extended') }} pe
USING (offer_id)
