version: 2
# Зависимости:
# + posting_item_odm
# hub_products \ _ + products_extended, + products_list / hub_product
# sat_products /                                        \ sat_product_wide
# product_prices_odm    \ _ prices (+ product_prices)
# report_product_prices /
# report_products _ raw_report_products
# + transaction_odm
#
models:
- name: products
  description: Таблица с информацией о sku
  custom_sql:
  infra: pg
  source: ozon
  source_schema: dm
  source_table: products
  load_start_date: '2024-06-01'
  schedule: 0 2 * * *
  load_type: T-1
  depends_on: # Необходимо создать inlets datasets {{ source_schema }}_{{ model }}
    - ods_hub_products
    - ods_sat_products
    - odm_transaction_odm
    - odm_posting_item_odm
    - ods_report_products
    - ods_report_product_prices
    - odm_product_prices_odm
  affects_to: True
  alerting_chat_id: -1002165384587
  alerting_secret_name: home_urevoleg_alerting_bot_token
  columns:
  - name: dated_at
    description:  Дата расчета
    data_type: date
  - name: product_pk
    description:  Surrogate unique key
    data_type: bytea
  - name: primary_image
    description:  Product image
    data_type: character varying
  - name: product_name
    description:  Product name
    data_type: character varying
  - name: category_comission
    description:  Category
    data_type: character varying
  - name: brand
    description:  Бренд
    data_type: character varying
  - name: offer_id
    description:  Артику
    data_type: character varying
  - name: product_id
    description:  ID продукта
    data_type: bigint
  - name: fbo_sku
    description:  OZON FBO SKU
    data_type: bigint
  - name: fbs_sku
    description:  OZON FBS SKU
    data_type: bigint
  - name: barcode
    description:  Штрихкод
    data_type: character varying
  - name: price
    description:  Цена
    data_type: numeric
  - name: current_price
    description:  Текущая цена
    data_type: numeric
  - name: fbo_free_to_sell_amount
    description:  Кол-во FBO доступных для продажи
    data_type: bigint
  - name: fbs_free_to_sell_amount
    description:  Кол-во FBS доступных для продажи
    data_type: bigint
  - name: rfbs_free_to_sell_amount
    description:  Кол-во RFBS доступных для продажи
    data_type: bigint
  - name: reserved_amount
    description:  Кол-во зарезервированных
    data_type: bigint
  - name: seller_reserved_amount
    description:  Кол-во зарезервированных продавцом
    data_type: bigint
  - name: orders_amount
    description:  Кол-во заказов
    data_type: bigint
  - name: transactions_amount
    description:  Кол-во транзакций (выкупы)
    data_type: bigint
  - name: accruals_for_sale
    description:  Кол-во начислений за продажу
    data_type: double precision
  - name: repurchase
    description:  Выкупы, % (для конкретного продукта)
    data_type: numeric
  - name: min_price
    description:  Минимальная цена (цена установленная поставщиком)
    data_type: numeric
  - name: marketing_seller_price
    description:  Маркетинговая цена продавца (цена с учетом соинвеста OZON)
    data_type: numeric

